name: Run Python Scripts and Commit CSV Files

on:
  workflow_dispatch:  # Triggered manually
  # schedule:
  #  - cron: '0 0,12 * * *'  # Run every 12 hours

jobs:
  build:
    name: MF Holdings
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Ensure correct Python version is installed

      - name: Check for CSV Files
        run: |
          if [ -n "$(find . -maxdepth 1 -name '*.csv' -print -quit)" ]; then
            echo "CSV files found. Deleting..."
            find . -type f -name "*.csv" -delete
          else
            echo "No CSV files found. Skipping deletion."
          fi

      - name: Install dependencies in virtual environment
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          python -m pip install --upgrade pip  # Upgrade pip within venv
          pip install -r requirements.txt  # Install dependencies

      - name: Run Python Scripts
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          source venv/bin/activate  # Activate virtual environment
          python MFCode.py
          python Benchmark.py
          python "Historical Returns.py"
          python "Index Latest.py"
          python "Peer Comparison.py"
          python "Scheme Risk.py"
          python "Returns Data.py"
          
      - name: Commit CSV files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Add CSV files
          git commit -m "Auto-commit CSV files" || echo "No CSV files to commit, skipping commit"
          git push || echo "No changes to push"
